name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    # This is the magic step for embedded Rust!
      # It installs the compiler and the specific architecture target for your STM32.
    - name: Install Rust Toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: thumbv7em-none-eabihf 

      # Caching speeds up your workflow by saving downloaded crates between runs
    - name: Setup Rust Cache
      uses: Swatinem/rust-cache@v2

      # The actual build command.
      # If you have a .cargo/config.toml setting your default target, this is all you need!
    - name: Check Build (Release)
      run: cargo build --release
